airflow_data_fellowship:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: "{{ env_var('DBT_CLICKHOUSE_HOST', 'localhost') }}"
      port: 8123
      user: default
      password: clickhouse
      secure: false
